[package]
name = "pvm"
version = "0.1.0"
edition = "2021"

[lib]
name = "pvm"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pvm-rust = { git = "https://github.com/jamixir/pvm-rust" }
rustler = "0.34.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
