[package]
name = "bandersnatch_ring_vrf"
version = "0.1.0"
edition = "2024"
authors = [ "Baruch Fishman" ]

[lib]
name = "bandersnatch_ring_vrf"
path = "src/lib.rs"
crate-type = ["cdylib"]


[dependencies]
ark-ec-vrfs = { git = "https://github.com/daiagi/ark-ec-vrfs", features = [
    "bandersnatch",
    "ring",
    "parallel",
    "test-vectors",
] }
ring-proof = { package = "ring", git = "https://github.com/daiagi/ring-proof", branch = "extended", default-features = false }
ark-ec = { version = "0.4", default-features = false }
ark-serialize = { version = "0.4", default-features = false, features = ["derive"] }
hex = "0.4.3"
rustler = "0.34.0"
rand_chacha = { version = "0.3", default-features = false }
