[package]
name = "bandersnatch_ring_vrf"
version = "0.1.0"
edition = "2021"

[lib]
name = "bandersnatch_ring_vrf"
path = "src/lib.rs"
crate-type = ["cdylib"]


[dependencies]
ark-ec-vrfs = { git = "https://github.com/davxy/ark-ec-vrfs", features = [
    "bandersnatch",
    "ring",
    "parallel",
    "test-vectors",
] }
hex = "0.4.3"
rustler = "0.34.0"
