name: Build and Release

on:
  push:
    tags:
      - 'gp-*.*.*_app-*.*.*'          # GP releases, e.g. gp-0.6.6_app-0.6.6

jobs:
  build:
    name: Build ${{ matrix.platform }} ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
        env: [prod, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git for private deps
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.2"
          otp-version: "27.0.1"

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: MIX_ENV=${{ matrix.env }} mix compile

      - name: Build Release
        run: MIX_ENV=${{ matrix.env }} mix release --overwrite

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.env }}-${{ matrix.platform }}-${{ github.ref_name }}
          path: _build/${{ matrix.env }}/rel/**

  publish:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/**
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}