name: Jam Test Vectors
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Build and run test vectors
    runs-on: ubuntu-latest
    env:
      VECTORS_OWNER: davxy
      VECTORS_REPO: jam-test-vectors
      VECTORS_BRANCH: master
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git for private deps
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.2"
          otp-version: "27.0.1"

      - name: Restore cached build
        id: cache-build-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            _build
            deps
            priv/native
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-${{ hashFiles('native/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile test and full_test environments
        run: |
          MIX_ENV=test mix compile
          MIX_ENV=full_test mix compile

      - name: Save build cache
        uses: actions/cache/save@v4
        if: steps.cache-build-restore.outputs.cache-hit != 'true'
        with:
          path: |
            _build
            deps
            priv/native
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-${{ hashFiles('native/**/Cargo.lock') }}

      - name: Get latest test vectors commit hash
        id: get-vector-hash
        run: |
          LATEST_HASH=$(git ls-remote https://github.com/${{ env.VECTORS_OWNER }}/${{ env.VECTORS_REPO }}.git refs/heads/${{ env.VECTORS_BRANCH }} | awk '{ print $1 }')
          echo "LATEST_HASH=$LATEST_HASH" >> $GITHUB_ENV

      - name: Restore test vectors cache
        id: cache-vectors-restore
        uses: actions/cache/restore@v4
        with:
          path: jam-test-vectors-cache
          key: test-vectors-${{ env.LATEST_HASH }}

      - name: Clone test vectors if repo is updated
        if: steps.cache-vectors-restore.outputs.cache-hit != 'true'
        run: |
          rm -rf jam-test-vectors-cache
          git clone -b ${{ env.VECTORS_BRANCH }} https://github.com/${{ env.VECTORS_OWNER }}/${{ env.VECTORS_REPO }}.git jam-test-vectors-cache
          git -C jam-test-vectors-cache rev-parse HEAD > jam-test-vectors-cache/latest_commit.txt

      - name: cache test vectors repo if it's updated
        if: steps.cache-vectors-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: jam-test-vectors-cache
          key: test-vectors-${{ env.LATEST_HASH }}

      - name: Move cached test vectors to expected location
        run: mv jam-test-vectors-cache ../jam-test-vectors

      - name: Run tiny vector tests
        run: mix test --only tiny_vectors
      - name: Run full vector tests
        env:
          MIX_ENV: full_test
        run: mix test --only full_vectors
      - name: Run slow tests
        run: mix test --only slow
