name: Elixir Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git for private deps
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.2'
          otp-version: '27.0.1'

      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
            native
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-${{ hashFiles('native/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Remove invalid test files
        run: find deps/x509/test/data/ -name "*.tools.ietf.org.cer" -delete || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            _build
            deps
            native

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Get latest test vectors commit hash
        id: get-vector-hash
        run: |
          LATEST_HASH=$(git ls-remote https://github.com/davxy/jam-test-vectors.git refs/heads/polkajam-vectors | awk '{ print $1 }')
          echo "LATEST_HASH=$LATEST_HASH" >> $GITHUB_ENV

      - name: Restore test vectors cache
        id: cache-vectors-restore
        uses: actions/cache@v4
        with:
          path: ../jam-test-vectors
          key: test-vectors-${{ env.LATEST_HASH }}

      - name: Clone test vectors if repo is updated
        if: steps.cache-vectors-restore.outputs.cache-hit != 'true'
        run: |
          cd ..
          git clone -b polkajam-vectors https://github.com/davxy/jam-test-vectors.git
          cd jam-test-vectors
          git rev-parse HEAD > latest_commit.txt
          cd $GITHUB_WORKSPACE

      - name: Save latest commit hash to cache
        uses: actions/cache@v4
        with:
          path: ../jam-test-vectors
          key: test-vectors-${{ env.LATEST_HASH }}

      - name: Run standard tests
        run: mix test --exclude tiny_vectors --exclude full_vectors 
      - name: Run tiny vector tests
        run: mix test --only tiny_vectors

      - name: Run full vector tests
        env:
          MIX_ENV: full_test
        run: mix test --only full_vectors 
