name: Elixir Tests


on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - test-gh-workflow


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Git for private deps
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.2'
          otp-version: '27.0.1'

      - name: Restore cached build
        id: cache-build-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            _build
            deps
            native
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-${{ hashFiles('native/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        if: steps.cache-build-restore.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile dependencies and project
        if: steps.cache-build-restore.outputs.cache-hit != 'true'
        run: |
          mix deps.compile
          mix compile

      - name: Save build cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            _build
            deps
            native
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}-${{ hashFiles('native/**/Cargo.lock') }}

      - name: Run tests with full_vectors
        run: mix test --include full_vectors  --timeout 300000